web_site:
    resource: "@WebSiteBundle/Controller/"
    type:     annotation
    prefix:   /

logout:
    path: /logout

comur_image:
    resource: "@ComurImageBundle/Resources/config/routing.yml"
    prefix:   /admin/

fos_js_routing:
    resource: "@FOSJsRoutingBundle/Resources/config/routing/routing.xml"
